import {z} from "zod";
import {prisma} from "@/lib/prisma";
import {apiError,AppError} from "@/lib/http";
import {requirePermission} from "@/lib/rbac";
import {requireSession} from "@/lib/session";

const schema=z.object({name:z.string().trim().min(2).max(120).optional(),category:z.string().trim().min(2).max(80).optional(),unit:z.string().trim().min(1).max(30).optional(),minimumStockLevel:z.number().nonnegative().optional(),maximumStockLevel:z.number().positive().nullable().optional(),unitCost:z.number().nonnegative().nullable().optional(),description:z.string().trim().max(1000).nullable().optional(),status:z.enum(["ACTIVE","INACTIVE"]).optional()});
export async function PATCH(request:Request,{params}:{params:Promise<{id:string}>}){try{const user=await requireSession();requirePermission(user.role,"inventory:manage");const{id}=await params;const input=schema.parse(await request.json());const before=await prisma.inventoryItem.findUnique({where:{id},include:{category:true}});if(!before)throw new AppError(404,"ITEM_NOT_FOUND","Inventory item was not found.");const updated=await prisma.$transaction(async tx=>{const category=input.category?await tx.inventoryCategory.upsert({where:{name:input.category},update:{status:"ACTIVE"},create:{name:input.category}}):null;const row=await tx.inventoryItem.update({where:{id},data:{name:input.name,categoryId:category?.id,unit:input.unit,minimumStockLevel:input.minimumStockLevel,maximumStockLevel:input.maximumStockLevel,unitCost:input.unitCost,description:input.description,status:input.status}});await tx.auditLog.create({data:{userId:user.id,action:input.status==="INACTIVE"?"INVENTORY_ITEM_DEACTIVATED":"INVENTORY_ITEM_UPDATED",entityType:"InventoryItem",entityId:id,previousValue:{name:before.name,category:before.category.name,unit:before.unit,minimum:before.minimumStockLevel.toString(),status:before.status},newValue:{name:row.name,unit:row.unit,minimum:row.minimumStockLevel.toString(),status:row.status}}});return row});return Response.json({item:updated})}catch(error){return apiError(error)}}
export async function DELETE(_:Request,{params}:{params:Promise<{id:string}>}){try{const user=await requireSession();requirePermission(user.role,"inventory:manage");const{id}=await params;const item=await prisma.inventoryItem.findUnique({where:{id}});if(!item)throw new AppError(404,"ITEM_NOT_FOUND","Inventory item was not found.");await prisma.$transaction([prisma.inventoryItem.update({where:{id},data:{status:"INACTIVE"}}),prisma.auditLog.create({data:{userId:user.id,action:"INVENTORY_ITEM_DEACTIVATED",entityType:"InventoryItem",entityId:id,previousValue:{status:item.status},newValue:{status:"INACTIVE"}}})]);return new Response(null,{status:204})}catch(error){return apiError(error)}}
