import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { apiError, AppError } from "@/lib/http";
import { requirePermission } from "@/lib/rbac";
import { requireSession } from "@/lib/session";

const updateSchema=z.object({companyName:z.string().trim().min(2).max(120).optional(),contactPerson:z.string().trim().max(120).nullable().optional(),contactPhone:z.string().trim().max(30).nullable().optional(),contactEmail:z.union([z.email(),z.literal(""),z.null()]).optional(),address:z.string().trim().max(300).nullable().optional(),notes:z.string().trim().max(1000).nullable().optional(),status:z.enum(["ACTIVE","INACTIVE"]).optional()});

export async function PATCH(request:Request,{params}:{params:Promise<{id:string}>}) {try{const user=await requireSession();requirePermission(user.role,"clients:manage");const {id}=await params;const input=updateSchema.parse(await request.json());const before=await prisma.client.findUnique({where:{id}});if(!before)throw new AppError(404,"CLIENT_NOT_FOUND","Client was not found.");const client=await prisma.$transaction(async tx=>{const updated=await tx.client.update({where:{id},data:{...input,contactEmail:input.contactEmail||null}});await tx.auditLog.create({data:{userId:user.id,action:"CLIENT_UPDATED",entityType:"Client",entityId:id,previousValue:{companyName:before.companyName,status:before.status},newValue:{companyName:updated.companyName,status:updated.status}}});return updated});return Response.json({client})}catch(error){return apiError(error)}}
export async function DELETE(_:Request,{params}:{params:Promise<{id:string}>}) {try{const user=await requireSession();requirePermission(user.role,"clients:manage");const {id}=await params;const before=await prisma.client.findUnique({where:{id}});if(!before)throw new AppError(404,"CLIENT_NOT_FOUND","Client was not found.");await prisma.$transaction([prisma.client.update({where:{id},data:{status:"INACTIVE"}}),prisma.auditLog.create({data:{userId:user.id,action:"CLIENT_DEACTIVATED",entityType:"Client",entityId:id,previousValue:{status:before.status},newValue:{status:"INACTIVE"}}})]);return new Response(null,{status:204})}catch(error){return apiError(error)}}
